### ISSUE TITLE
TypeError: Layer flatten does not support masking, but was passed an input_mask: Tensor("concatenate_3/All:0", shape=(None, 1), dtype=bool)

### ISSUE THREAD

**Issue by fangxy926** [kishimoto-banana/DeepInterestNetwork#1]
![image](https://user-images.githubusercontent.com/23739775/60766364-4e182d00-a0db-11e9-98d1-e0e3419b0f18.png)
I am running on `tensorflow==2.0.0-alpha0`, is that the cause of error?

**Comment by songyaheng** [comment]
you can replace the model.py file  in line “embeddings = tf.keras.layers.Flatten()(embeddings)” with "embeddings = tf.keras.layers.Flatten().call(embeddings)"
